export const rooms = {
	room1: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room2: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room3: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room4: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room5: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room6: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room7: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room8: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room9: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room10: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room11: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
	room12: {
		userCount: 0,
		roundNumber: 0,
		turn: {
			start: false,
			timeStart: 0.0,
			timeTotal: 0,
		},
		currentWord: "",
		currentDrawer: "",
		currentDrawerId: "",
		points: {},
		usersGuessed: 0,
		usersGuessedName: [],
		turnNumber: 0,
		turnOn: false,
		wordRevealInterval: null,
		timeout: null,
		cleared: false,
		cache: {
			indexes: [],
			letters: [],
		},
		users: {},
		keys: [],
		startCount: 0,
	},
};

export const words = [
	"pencil",
	"paper",
	"glasses",
	"bottle",
	"keyboard",
	"clouds",
	"hills",
	"glue",
	"keys",
	"cuboid",
	"laptop",
	"window",
	"shoe",
	"play station",
];

export const players = {}; // socket_id -> room
